image: python:latest

build:
  stage: build
  script:
    - pip install poetry
    - poetry install
    - dephell deps convert

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=grogarium --api-key=$HEROKU_API_KEY
  only:
    - trunk
