prefixes = ["Gr!", "gr!", "GR!"]
case-insensitive = true
description = """Grogarium - A discord bot that works.
This bot is created by TonyBrown148.
You can find the source code at here:
https://github.com/tb148/grogarium"""
ready = [
    "Grogar is connected!",
    "INIT: GROGAR.BOT",
    "Grogar's body is ready!",
    "Grogar is ready to roll!",
    "Grogar is now running.",
    "Now loading Grogar...",
    "Grogar is now formatting C:\\ drive...Just kidding!",
    "Grogar is offlinen't!",
    "All systems go.",
    "Grogar is now up and running.",
    "Grogar: \"Let's do this!\"",
    "Grogar has entered the chat",
    "It's a bird! It's a plane! Wait, no, it's just Grogar.",
]
status = [
    "Try Gr!help",
    "Send Gr!help",
    "Type Gr!help",
    "PREFIX = MENTION",
    "Mention me before commands",
    "My prefix is my mention",
    "with the Discord API",
    "with Python",
    "with discord.py",
]
stat-freq = 10.0
error = [
    "What am I expected to do then?",
    "What are you expecting me to do?",
    "Wait what? Are you serious?",
    "Are you sure that this is exactly what you mean?",
]
owners = [728198677050425424]
logfile = "grogar.log"

[roll]
enabled = true
hidden = false
help = "Rolls some dice"
aliases = ["dice"]

[roll.one-faced]
every = false
any = true

[roll.limits]
count = 400
size = 400

[roll.default]
count = 1
size = 6

[roll.warnings]
limits = [
    "Are you testing my functionalities or what?",
    "Don't test me anymore! I am stable!",
]
one-faced = [
    "Wow! You can predict the future!",
    "Guess what the answer is? Wow, you get it right!",
]

[8ball]
enabled = true
hidden = false
help = "Answers a question"
aliases = ["8_ball", "8-ball", "eightball", "eight-ball", "eight_ball"]
answers = [
    "Yes",
    "It is certain",
    "Of course",
    "100 percent!",
    "Definitely",
    "Maybe",
    "Perhaps",
    "Not sure",
    "Reply hazy, try again",
    "Who knows?",
    "No",
    "Of course not",
    "Never",
    "Absolutely not",
    "Not a chance",
]

[ping]
enabled = true
hidden = false
help = "Tests the connection"
aliases = ["pong", "test", "network"]

[util]
name = "Utility"
description = "Utilities that are not designed for fun"

[calc]
enabled = true
hidden = false
help = "Does some math"
aliases = ["calculate", "math"]

[trans]
enabled = true
hidden = false
help = "Translates something"
aliases = ["translate", "gt"]

[langs]
enabled = true
hidden = false
help = "Outputs all the langcodes"
aliases = ["lang", "langcodes", "langcode"]

[fun]
name = "Fun"
description = "Fun commands that are not games"

[badgt]
enabled = true
hidden = false
help = "Translates something badly"
aliases = ["badtranslate", "bgt", "bt"]
limit = 25
warnings = [
    "Are you testing my functionalities or what?",
    "Don't test me anymore! I am stable!",
]

[slap]
enabled = true
hidden = false
help = "Slaps somebody"
aliases = ["hand", "ultraslap"]

[game]
enabled = true
hidden = false
help = "Plays the game"
aliases = ["thegame"]
win-chance = 0.05

[necro]
enabled = true
hidden = false
help = "Plays thread necromancy"
aliases = ["necromancy", "necropost"]
posts = 500
bot = false
limit = 10000
warning = [
    "Are you testing my functionalities or what?",
    "Don't test me anymore! I am stable!",
]

[burn]
enabled = true
hidden = false
help = "Print some Lyrics"
aliases = ["nces"]
lyrics = [
    "Living in a crazy world",
    "Following the path that always twists and turns",
    "Gave up on your sanity to hide behind the devil",
    "Cuz you think you'll live forever",
    "Saying that you're getting old",
    "Out there thinking that you're in the world alone",
    "No one ever told you that you have to live for something",
    "Or in the end, you will be nothing",
    "It's too cold",
    "Standing in the middle of the downpour",
    "Looking in the mirror cuz it's only you",
    "That you have to lose",
    "Heading back with only one way",
    "Trying to stop from running but you can't wait",
    "Bury all the evidence",
    "You'll only learn",
    "When you crash and burn"
]
freq = 5

[imag]
name = "Imaginary Image"
description = "Imaginary images generated by StyleGANs"

[human]
enabled = true
hidden = false
help = "This Human Does Not Exist"
aliases = ["person", "humans"]

[arts]
enabled = true
hidden = false
help = "This Artwork Does Not Exist"
aliases = ["art", "artwork"]

[cats]
enabled = true
hidden = false
help = "This Cat Does Not Exist"
aliases = ["cat"]

[horse]
enabled = true
hidden = false
help = "This Horse Does Not Exist"
aliases = ["horses"]

[usr]
name = "User"
description = "Use this bot as an user"

[tbgs]
name = "TBGforums"
description = "Syncs messages"

[sync]
enabled = true
hidden = false
help = "Syncs messages"
aliases = ["post"]
sync-freq = 180
