prefix = "%"
case-insensitive = true
description = "Grogarium - A discord bot that works. This bot is created by TonyBrown148. You can find the source code at here: https://github.com/tb148/grogarium\n"
ready = [
    "Grogar is connected!",
    "INIT: GROGAR.BOT",
    "Grogar's body is ready!",
    "Grogar is ready to roll!",
    "Grogar is now running.",
    "Now loading Grogar...",
    "Grogar is now formatting C:\\ drive...Just kidding!",
    "Grogar is offlinen't!",
    "All systems go.",
    "Grogar is now up and running.",
    "Grogar: \"Let's do this!\"",
    "Grogar has entered the chat",
    "It's a bird! It's a plane! Wait, no, it's just Grogar.",
]
status = [
    "Try %help",
    "Send %help",
    "Type %help",
    "PREFIX = SHIFT + 5",
    "Add % before commands",
    "My prefix is %",
    "with the Discord API",
    "with Python",
    "with discord.py",
]
stat-freq = 10.0
error = [
    "What am I expected to do then?",
    "What are you expecting for me to do?",
    "Wait what? Are you serious?",
    "Don't test me anymore! I am stable!",
    "Please DO NOT open an issue for this.",
]
owners = [728198677050425424]
logfile = "grogar.log"

[roll]
enabled = true
hidden = false
help = "Roll some dice."
brief = "Roll dice"
usage = "[<size>|<count> <size>|<sizes>...]"
aliases = ["dice"]

[roll.one-faced]
every = false
any = true

[roll.limits]
count = 400
size = 400

[roll.default]
count = 1
size = 6

[roll.warnings]
limits = [
    "Are you testing my functionalities or what?",
    "Don't test me anymore! I am stable!",
]
one-faced = [
    "Wow! You can predict the future!",
    "Guess what the answer is? Wow, you get it right!",
]

[8ball]
enabled = true
hidden = false
help = "Ask a question, get an answer."
brief = "Answer questions"
usage = "<question>"
aliases = ["8_ball", "8-ball", "eightball", "eight-ball", "eight_ball"]
answers = [
    "Yes",
    "It is certain",
    "Of course",
    "100 percent!",
    "Definitely",
    "Maybe",
    "Perhaps",
    "Not sure",
    "Reply hazy, try again",
    "Who knows?",
    "No",
    "Of course not",
    "Never",
    "Absolutely not",
    "Not a chance",
]

[ping]
enabled = true
hidden = false
help = "Test the internet connection of the bot."
brief = "Ping"
usage = ""
aliases = ["pong", "test", "network"]

[calc]
enabled = true
hidden = false
help = "Calculate and/or simplify mathematical expressions. Certain symbols may be used."
brief = "Calculate"
usage = "<expression>"
aliases = ["calculate", "math"]

[trans]
enabled = true
hidden = false
help = "Translate a word or sentence to another language."
brief = "Google translate"
usage = "<src> <dest> <text>"
aliases = ["translate", "gt"]

[langs]
enabled = true
hidden = false
help = "Output a list that contains all the langcodes you can use."
brief = "Get the langcodes"
usage = ""
aliases = ["lang", "langcodes", "langcode"]

[badgt]
enabled = true
hidden = false
help = "Badly translate a word or sentence to another language."
brief = "Bad Google translate"
usage = "<src> <count> <dest> <text>"
aliases = ["badtranslate", "bgt", "bt"]
limit = 100
warnings = [
    "Are you testing my functionalities or what?",
    "Don't test me anymore! I am stable!",
]

[slap]
enabled = true
hidden = false
help = "Slaps somebody."
brief = "Slaps"
usage = "<users> ..."
aliases = ["hand", "ultraslap"]

[game]
enabled = true
hidden = false
help = "Plays the game. See https://en.wikipedia.org/wiki/The_Game_(mind_game)"
brief = "The game"
usage = ""
aliases = ["thegame"]
win-chance = 0.01

[necro]
enabled = true
hidden = false
help = "Plays thread necromancy."
brief = "Necropost"
usage = "<channel> [posts] [leaderboard]"
aliases = ["necromancy", "necropost"]
posts = 500
top = false
bot = false

[human]
enabled = true
hidden = false
help = "This Human Does Not Exist."
brief = "For humans"
usage = ""
aliases = ["person", "humans"]

[arts]
enabled = true
hidden = false
help = "This Artwork Does Not Exist."
brief = "For artworks"
usage = ""
aliases = ["art", "artwork"]

[cats]
enabled = true
hidden = false
help = "This Cat Does Not Exist."
brief = "For cats"
usage = ""
aliases = ["cat"]

[horse]
enabled = true
hidden = false
help = "This Horse Does Not Exist."
brief = "For horses"
usage = ""
aliases = ["horses"]
