[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool]

[tool.poetry]
name = "grogarium"
version = "0.3.0-alpha"
description = "A discord bot that works."
license = "AGPL-3.0-or-later"
authors = ["Tony Brown <tb148@tuta.io>"]
maintainers = ["Tony Brown <tb148@tuta.io>"]
readme = "README.md"
repository = "https://github.com/tb148/grogarium/"

[tool.poetry.dependencies]
python = "^3.8.3"
aiohttp = { extras = ["speedups"], version = "^3.6.2" }
"discord.py" = { extras = ["voice"], version = "^1.4.1" }
googletrans = "^3.0.0"
sympy = "^1.6.2"
toml = "^0.10.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
dpytest = "^0.0.21"
coverage = "^5.3"
dephell = { extras = ["full"], version = "^0.8.3" }
commitizen = "^2.4.0"

[tool.dephell.main]
from = { format = "poetry", path = "pyproject.toml" }
to = { format = "pip", path = "requirements.txt" }
