name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Hi! It seems like this issue didn''t get enough attention, so it will be closed as stale.'
        stale-pr-message: 'Hi! It seems like this PR didn''t get enough attention, so it will be closed as stale.'
        stale-issue-label: 'status - stale'
        stale-pr-label: 'status - stale'
