name: Format code using Prettier and Black
on: push

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Prettier
        run: npm install --global prettier prettier-plugin-toml
      - name: Check format
        run: prettier --check .
      - name: Format code
        if: failure()
        run: prettier --write .
      - name: Commit changed files
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: format code"
  black:
    runs-on: ubuntu-latest
    needs: prettier
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install black
        run: pip install black
      - name: Check format
        run: black --check -l 80 .
      - name: Format code
        if: failure()
        run: black -l 0 . && black -l 80 .
      - name: Commit changed files
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: format code"
