name: Format code using Prettier and Black
on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Prettier
        run: npm install --global prettier
      - name: Check format
        run: npx prettier --check .
      - name: Format code
        if: failure()
        run: npx prettier --write .
      - name: Commit changed files
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: format code"
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install Black
        run: pip install black
      - name: Check format
        run: black --check .
      - name: Format code
        if: failure()
        run: black .
      - name: Commit changed files
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: format code"
