name: Format code using Prettier
on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Installl black
        run: pip install black
      - name: Check format
        run: black --check .
      - name: Format code
        if: failure()
        run: black .
      - name: Commit changed files
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: format code"
